FROM cloudflare/cloudflared:latest
CMD ["tunnel", "--no-autoupdate", "run", "--token", "${eyJhIjoiOTkyYWIzOGQ2ZWIzM2Q2Mzc0MDgwNGI4YTQwNWUxMzYiLCJ0IjoiNzQ4OTE0NjYtOTE4MS00Njg4LTljMDUtNjljM2ZmNjE0MDFkIiwicyI6Ik5UQm1aamhqTVRndE56TmhPUzAwTXpJeExXRmxaREl0TmpnNE56VTRZV0U0TXpVNCJ9}"]
